apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashmaster
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashmaster
  template:
    metadata:
      labels:
        app: dashmaster
    spec:
      containers:
      - name: dashmaster
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: dashmaster-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dashmaster
