---
apiVersion: v1
kind: Secret
metadata:
  name: dashmaster-secrets
stringData:
  # Store sensitive information as Kubernetes secrets
  # Replace these placeholder values with actual credentials in a production environment
  # Consider using a secrets management solution in production
  TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}" # Replace with actual token when deploying
  DB_PASSWORD: "${DB_PASSWORD}" # Replace with actual password when deploying
  DB_URL: "${DB_URL}" # Database connection string from environment variable
  DB_USERNAME: "${DB_USERNAME}" # Database username from environment variable
  TNS_ADMIN_PATH: "src/main/resources/Wallet_javadev" # Path to wallet
  DRIVER_CLASS_NAME: "oracle.jdbc.OracleDriver" # Database driver class name
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashmaster-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashmaster-backend
  template:
    metadata:
      labels:
        app: dashmaster-backend
    spec:
      containers:
      - name: dashmaster-backend
        image: ${BACKEND_IMAGE}
        ports:
        - containerPort: 8080
        env:
        # Reference secrets securely via secretKeyRef
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: dashmaster-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dashmaster-secrets
              key: DB_PASSWORD
        - name: spring.datasource.url
          valueFrom:
            secretKeyRef:
              name: dashmaster-secrets
              key: DB_URL
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: dashmaster-secrets
              key: DB_USERNAME
        - name: spring.datasource.driver-class-name
          valueFrom:
            secretKeyRef:
              name: dashmaster-secrets
              key: DRIVER_CLASS_NAME
        # TNS_ADMIN points to the wallet path INSIDE the container
        - name: TNS_ADMIN
          valueFrom:
            secretKeyRef:
              name: dashmaster-secrets
              key: TNS_ADMIN_PATH
      imagePullSecrets:
      - name: ocir-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashmaster-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashmaster-frontend
  template:
    metadata:
      labels:
        app: dashmaster-frontend
    spec:
      containers:
      - name: dashmaster-frontend
        image: ${FRONTEND_IMAGE}
        ports:
        - containerPort: 3000
        env:
        # API base URL for frontend to communicate with backend
        - name: VITE_API_BASE_URL
          value: "/api"
      imagePullSecrets:
      - name: ocir-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dashmaster-backend-service
spec:
  selector:
    app: dashmaster-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP # Internal service not exposed directly outside the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: dashmaster-frontend-service
spec:
  selector:
    app: dashmaster-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP # Internal service accessed through Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashmaster-ingress
  annotations:
    # Specifies NGINX as the ingress controller implementation
    kubernetes.io/ingress.class: "nginx"
    # Rewrites request paths for proper routing
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      # Route /api requests to the backend service
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: dashmaster-backend-service
            port:
              number: 8080
      # Route /auth requests to the backend service
      - path: /auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: dashmaster-backend-service
            port:
              number: 8080
      # Route all other requests to the frontend service
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: dashmaster-frontend-service
            port:
              number: 3000