version: '3.8'

services:
  db:
    image: h2:latest
    ports:
      - "9092:9092"
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - h2-data:/h2-data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_USER=${DB_USER:-TODOUSER}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - UI_USERNAME=${UI_USERNAME:-admin}
      - UI_PASSWORD=${UI_PASSWORD:-admin}
      - JWT_SECRET=${JWT_SECRET:-defaultSecretKeyForLocalDevelopmentEnvironmentOnly}
      - OCI_CONFIG_FILE=/root/.oci/config
    volumes:
      - ~/.oci:/root/.oci
    depends_on:
      - db

volumes:
  h2-data:
