apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashmaster
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashmaster
  template:
    metadata:
      labels:
        app: dashmaster
    spec:
      containers:
      - name: dashmaster
        image: dashmaster:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:oracle:thin:@javadev_high?TNS_ADMIN=/app/wallet"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: jwt-secret
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: telegram-bot-token
        - name: TELEGRAM_BOT_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: telegram-bot-name
        volumeMounts:
        - name: wallet-volume
          mountPath: /app/wallet
      volumes:
      - name: wallet-volume
        secret:
          secretName: oracle-wallet
---
apiVersion: v1
kind: Service
metadata:
  name: dashmaster-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: dashmaster
