FROM openjdk:11-jdk-slim

WORKDIR /app

# Copy the JAR file
COPY target/MyTodoList-0.0.1-SNAPSHOT.jar app.jar

# Environment variables set at runtime

# Run the JAR file
ENTRYPOINT ["java", "-Dspring.profiles.active=local", "-jar", "app.jar"]
