-- Create our todo table if it doesn't exist
CREATE TABLE IF NOT EXISTS TODOITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(4000),
    CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DONE BOOLEAN DEFAULT FALSE
);

-- Insert sample data
INSERT INTO TODOITEM (DESCRIPTION, DONE) VALUES ('Example to-do item', FALSE);
INSERT INTO TODOITEM (DESCRIPTION, DONE) VALUES ('Completed example', TRUE);
