apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
stringData:
  db-username: JAVADEV103
  db-password: Spring-boot103
  jwt-secret: 5qP0TFBDjFlfHeJ/qCJhce88Ep4nwn8B29iQZzPLEcKz+jXeEIsaF9eZYj3YZg5J
  telegram-bot-token: 7818362029:AAHjytZcyWk66nNzI3-KIDBbSuonVAymORA
  telegram-bot-name: team34_java_bot