name: Frontend Lint and Format

on:
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      working-directory: ./MtdrSpring/frontend
      run: bun install

    - name: Run ESLint
      working-directory: ./MtdrSpring/frontend
      # Continue on error to show lint failures without blocking prettier
      continue-on-error: true
      run: bun lint

  format-check:
    runs-on: ubuntu-latest
    # Run regardless of lint job outcome
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      working-directory: ./MtdrSpring/frontend
      run: bun install

    - name: Check Prettier formatting
      working-directory: ./MtdrSpring/frontend
      run: bunx prettier --check . --config .prettierrc

  # format-apply:
  #   runs-on: ubuntu-latest
  #   # Only run on push to develop
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Setup Bun
  #     uses: oven-sh/setup-bun@v1
  #     with:
  #       bun-version: latest

  #   - name: Install dependencies
  #     working-directory: ./MtdrSpring/frontend
  #     run: bun install

  #   - name: Format with Prettier
  #     working-directory: ./MtdrSpring/frontend
  #     run: bunx prettier --write . --config .prettierrc

  #   - name: Commit formatting changes
  #     run: |
  #       git config --global user.name 'GitHub Actions'
  #       git config --global user.email 'actions@github.com'
  #       git add .
  #       git diff --quiet && git diff --staged --quiet || git commit -m "Apply prettier formatting [skip ci]"
  #       git push